[package]
name = "rsrun"
version = "0.1.4"
edition = "2024"

description = "An easy way to test rust projects"
license = "MIT"
repository = "https://github.com/Vaaris16/rsrun"
readme = "README.md"
keywords = ["rsrun"]
categories = ["command-line-utilities"]



[dependencies]
figlet-rs = "1.0.0"
notify = "8.2.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"
